### ISSUE TITLE
Possible to add multiple sources?

### ISSUE THREAD

**Issue by DeviaVir** [SocketCluster/loadbalancer#1]
This works great so far, but I'd like to add multiple daemons listening on different ports, and forwarding to different ports as well. If you try to run `loadbalancer` again, you'll get the message it's already running now, and it doesn't seem possible add another "sourcePort" to the config.

**Comment by DeviaVir** [comment]
Removed the check here:
https://github.com/DeviaVir/loadbalancer/commit/7e97a7fee7695556141069509c29ca2838ff571a

Which is of course hardly to be called a "fix", but it does allow `loadbalancer` to keep starting and listening on different sourcePorts (given you supply different configs, of course). Installing forever (`npm install -g forever`) then allows me to check up on things.

**Comment by jondubois** [comment]
Thanks for pointing out this use case and the workaround.
Actually if you make a pull request with that fix, I will accept it.

Then we just need to add an optional argument (index/PID/UID) to the 'loadbalancer stop' command so it would work just like forever. We will also need add a 'loadbalancer list' command.
Feel free to take on that task too if you have the time :p 

Otherwise I'll do it sometime tomorrow hopefully. In either case, your patch will do for now.

**Comment by DeviaVir** [comment]
For now it works as I intended, so that makes me very happy. 

I noticed that if you use `forever stop 1` that it'll kill all forever instances though, so I think this might be a tough one to crack. I'll see if I can add something later today, if you don't hear back from me- I probably failed miserably :+1:

**Comment by jondubois** [comment]
As of v0.9.24, launching multiple load balancer daemons is supported by the CLI.

A list command was added.
Also, you can now provide an optional index to the loadbalancer stop command to stop a specific instance.

The restart command was removed because its purpose has become ambiguous and it's not really needed - You can achieve the same thing by calling stop and then start.

Feel free to keep using forever if you feel that you need more control - They are compatible and loadbalancer uses forever behind the scenes.
