### ISSUE TITLE
IIS Node/Windows support?

### ISSUE THREAD

**Issue by BenAHammond** [SocketCluster/loadbalancer#4]
Has this been tested with IIS Node?

Is there a way to run this without using the global option, but instead as a script?

**Comment by jondubois** [comment]
The command line interface should work in Windows - I don't have much experience with IIS so you'll have to try it out. You can install loadbalancer locally using:

``` bash
npm install loadbalancer
```

This should put the module inside a node_modules folder. The main script is at loadbalancer/index.js using. To run, you can use this (example with --config argument):

``` bash
node index.js --config myconfigfile.json
```

Sorry for the delay in response.

**Comment by BenAHammond** [comment]
No apologies necessary, I really appreciate the help!

Another question for you: Is there a way to modify requests directly before they get forwarded?

I'd like to use IIS's built in kerberos configuration to force authentication and then pass that authentication back to my loadbalanced webheads. I'd also like to add in a custom header or two to secure the communication with the server with a shared key.

**Comment by jondubois** [comment]
You can block requests from being forwarded based on any information you like but you cannot change the requests.

The root issue there is that LoadBalancer.js works at the TCP layer - We could in theory make some changes to LoadBalancer.js to allow modifying HTTP requests, but this wouldn't work with HTTPS because these would be encrypted and you'd have to decrypt the traffic before you will be able to change it - This would introduce SSL certificate management challenges.

Not sure if this is worth adding this feature given that it would only affect plaintext protocols given that so much traffic is encrypted with SSL nowadays.

Right now, LoadBalancer.js just forwards TCP traffic exactly as is - That allows it to work with any TCP-based protocol regardless of whether it is encrypted or not.

If you need more control over the HTTP/HTTPS layer, you will need to use something like https://github.com/nodejitsu/node-http-proxy - But then you will still have to use SSL certs for HTTPS.
It gives you a bit of extra work to do though :(
